"""add stance to scores

Revision ID: 03a2527c293d
Revises: f4190b47a0ed
Create Date: 2026-03-19 20:00:27.750587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03a2527c293d'
down_revision: Union[str, None] = 'f4190b47a0ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scores', sa.Column('stance', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scores', 'stance')
    # ### end Alembic commands ###
