"""Initial tables

Revision ID: 9da1f380b46a
Revises: 81a9ef3cb4e1
Create Date: 2025-04-23 23:55:46.916272

"""
from typing import Sequence, Union
from sqlalchemy import Enum as SQLEnum
from backend.app.db.models import DebateModeEnum

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9da1f380b46a'
down_revision: Union[str, None] = '81a9ef3cb4e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    debate_mode_enum = SQLEnum(DebateModeEnum, name="debatemodeenum")
    debate_mode_enum.create(op.get_bind())
    op.create_table('scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('argument_id', sa.Integer(), nullable=False),
    sa.Column('logical_consistency', sa.Float(), nullable=True),
    sa.Column('evidence_support', sa.Float(), nullable=True),
    sa.Column('bias', sa.Float(), nullable=True),
    sa.Column('ethical_balance', sa.Float(), nullable=True),
    sa.Column('total_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['argument_id'], ['arguments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scores_id'), 'scores', ['id'], unique=False)
    op.drop_index('ix_evaluations_id', table_name='evaluations')
    op.drop_table('evaluations')
    op.add_column('arguments', sa.Column('text', sa.Text(), nullable=False))
    op.add_column('arguments', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.alter_column('arguments', 'speaker',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_column('arguments', 'content')
    op.drop_column('arguments', 'turn_number')
    op.add_column('debates', sa.Column('topic', sa.String(length=255), nullable=False))
    op.alter_column('debates', 'mode',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('one_vs_one', 'ai_vs_human', name='debatemodeenum'),
               existing_nullable=False, postgresql_using='mode::debatemodeenum')
    op.drop_column('debates', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('debates', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.alter_column('debates', 'mode',
               existing_type=sa.Enum('one_vs_one', 'ai_vs_human', name='debatemodeenum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('debates', 'topic')
    op.add_column('arguments', sa.Column('turn_number', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('arguments', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.alter_column('arguments', 'speaker',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('arguments', 'created_at')
    op.drop_column('arguments', 'text')
    op.create_table('evaluations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('argument_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('logical_consistency', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('evidence_support', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('bias', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ethical_balance', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['argument_id'], ['arguments.id'], name='evaluations_argument_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='evaluations_pkey')
    )
    op.create_index('ix_evaluations_id', 'evaluations', ['id'], unique=False)
    op.drop_index(op.f('ix_scores_id'), table_name='scores')
    op.drop_table('scores')
    debate_mode_enum = SQLEnum(DebateModeEnum, name="debatemodeenum")
    debate_mode_enum.drop(op.get_bind())
    # ### end Alembic commands ###
