"""add nlp to scores

Revision ID: f4190b47a0ed
Revises: 1af2256c65f3
Create Date: 2025-04-30 11:57:25.623929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4190b47a0ed'
down_revision: Union[str, None] = '1af2256c65f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scores', sa.Column('nlp_insights', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scores', 'nlp_insights')
    # ### end Alembic commands ###
